version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'

  app:
    build: .
    container_name: nest-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
    ports:
      - '3000:3000'
    depends_on:
      - mysql
